services:
  site-comptage-heure:
    image: ghcr.io/breizhhardware/site-comptage-heure:latest
    ports:
      - '3000:3000'
    volumes:
      - ./data:/app/prisma/data
    environment:
      - NEXTAUTH_SECRET=your_secret_key
      - NEXTAUTH_URL=http://localhost:3000
